apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-compliant-workload
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
      - name: app
        image: nginx:1.25.3
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
